// app/components/List.vue
<script lang="ts" setup>
const props = withDefaults(defineProps<{ items?: any[] }>(), { items: () => [] })

function isPrimitive(val: unknown): boolean {
  const t = typeof val
  return t === 'string' || t === 'number' || t === 'boolean'
}
</script>

<template>
  <ol class="list-inside list-decimal text-sm text-center sm:text-left w-full text-center">
    <li
      v-for="(item, i) in props.items"
      :key="i"
      :class="{ 'mb-2': i < props.items.length - 1 }"
    >
      <span v-if="isPrimitive(item)">{{ item }}</span>
      <component v-else :is="item" />
    </li>
  </ol>
</template>

// src/components/List.tsx
import { JSX } from "solid-js";

export const List = ({ items = [] }: { items: JSX.Element[] }) => (
  <ol class="list-inside list-decimal text-sm text-center sm:text-left font-[family-name:var(--font-geist-mono)]">
    {items.map((item, i) => (
      <li class={i < items.length - 1 ? "mb-2" : ""}>
        {item}
      </li>
    ))}
  </ol>
);
